export const SUPPORTED_LOCALES = Object.freeze(["en", "es", "vi"]);

const translations = {
  en: {
    pageTitle: "A City's Weather",
    subtitle: "Search for current conditions and a three-day forecast.",
    searchLabel: "Weather search",
    cityPlaceholder: "Enter a City",
    cityLabel: "City",
    getWeather: "Get Weather",
    loading: "Loading...",
    pauseMotion: "Pause motion",
    playMotion: "Play motion",
    motionReduced: "Motion reduced",
    emptyPrompt: "Enter a city to check its weather.",
    previousSearches: "Previous Searches",
    noPreviousSearches: "No previous searches",
    connect: "Connect with me",
    portfolio: "Portfolio",
    appCopyright: "Weather App © 2024",
    supportedLanguages: "Languages supported: English, Spanish, and Vietnamese.",
    sunCredit: "Sun icons created by Freepik - Flaticon",
    sunCreditTitle: "sun icons",
    area: "Area:",
    region: "Region:",
    unknown: "Unknown",
    conditionsUnavailable: "Conditions unavailable",
    feelsLike: "Feels like",
    observed: "Observed",
    changeUnit: "Change To °{unit}?",
    averageTemperature: "Avg Temp:",
    maximumTemperature: "Max Temp:",
    minimumTemperature: "Min Temp:",
    loadingWeather: "Loading weather for {city}…",
    notFound: "We couldn't find weather for “{city}.” Check the spelling and try again.",
    incomplete: "Weather details for “{city}” are incomplete. Please try again later.",
    serviceUnavailable: "The weather service is unavailable right now. Please try again.",
  },
  es: {
    pageTitle: "El clima de una ciudad",
    subtitle: "Consulta las condiciones actuales y el pronóstico de tres días.",
    searchLabel: "Búsqueda del clima",
    cityPlaceholder: "Ingresa una ciudad",
    cityLabel: "Ciudad",
    getWeather: "Ver el clima",
    loading: "Cargando...",
    pauseMotion: "Pausar movimiento",
    playMotion: "Reanudar movimiento",
    motionReduced: "Movimiento reducido",
    emptyPrompt: "Ingresa una ciudad para consultar el clima.",
    previousSearches: "Búsquedas anteriores",
    noPreviousSearches: "No hay búsquedas anteriores",
    connect: "Conéctate conmigo",
    portfolio: "Portafolio",
    appCopyright: "Aplicación del clima © 2024",
    supportedLanguages: "Idiomas disponibles: inglés, español y vietnamita.",
    sunCredit: "Iconos del sol creados por Freepik - Flaticon",
    sunCreditTitle: "iconos del sol",
    area: "Zona:",
    region: "Región:",
    unknown: "Desconocida",
    conditionsUnavailable: "Condiciones no disponibles",
    feelsLike: "Sensación térmica",
    observed: "Observado",
    changeUnit: "¿Cambiar a °{unit}?",
    averageTemperature: "Temp. media:",
    maximumTemperature: "Temp. máx.:",
    minimumTemperature: "Temp. mín.:",
    loadingWeather: "Cargando el clima de {city}…",
    notFound: "No encontramos el clima de “{city}”. Revisa la ortografía e inténtalo de nuevo.",
    incomplete: "Los datos meteorológicos de “{city}” están incompletos. Inténtalo más tarde.",
    serviceUnavailable: "El servicio meteorológico no está disponible en este momento. Inténtalo de nuevo.",
  },
  vi: {
    pageTitle: "Thời tiết của một thành phố",
    subtitle: "Xem điều kiện hiện tại và dự báo thời tiết ba ngày.",
    searchLabel: "Tìm kiếm thời tiết",
    cityPlaceholder: "Nhập tên thành phố",
    cityLabel: "Thành phố",
    getWeather: "Xem thời tiết",
    loading: "Đang tải...",
    pauseMotion: "Tạm dừng chuyển động",
    playMotion: "Tiếp tục chuyển động",
    motionReduced: "Đã giảm chuyển động",
    emptyPrompt: "Nhập tên thành phố để xem thời tiết.",
    previousSearches: "Tìm kiếm trước đây",
    noPreviousSearches: "Chưa có tìm kiếm nào",
    connect: "Kết nối với tôi",
    portfolio: "Hồ sơ năng lực",
    appCopyright: "Ứng dụng thời tiết © 2024",
    supportedLanguages: "Ngôn ngữ được hỗ trợ: tiếng Anh, tiếng Tây Ban Nha và tiếng Việt.",
    sunCredit: "Biểu tượng mặt trời do Freepik tạo - Flaticon",
    sunCreditTitle: "biểu tượng mặt trời",
    area: "Khu vực:",
    region: "Vùng:",
    unknown: "Không xác định",
    conditionsUnavailable: "Không có thông tin điều kiện",
    feelsLike: "Cảm giác như",
    observed: "Quan sát lúc",
    changeUnit: "Đổi sang °{unit}?",
    averageTemperature: "Nhiệt độ TB:",
    maximumTemperature: "Cao nhất:",
    minimumTemperature: "Thấp nhất:",
    loadingWeather: "Đang tải thời tiết cho {city}…",
    notFound: "Không tìm thấy thời tiết cho “{city}”. Hãy kiểm tra tên và thử lại.",
    incomplete: "Dữ liệu thời tiết cho “{city}” chưa đầy đủ. Vui lòng thử lại sau.",
    serviceUnavailable: "Dịch vụ thời tiết hiện không khả dụng. Vui lòng thử lại.",
  },
};

export function resolveLocale(preferredLanguages = []) {
  for (const language of preferredLanguages) {
    const baseLanguage = String(language).trim().toLowerCase().split(/[-_]/)[0];
    if (SUPPORTED_LOCALES.includes(baseLanguage)) return baseLanguage;
  }
  return "en";
}

export function translate(locale, key, replacements = {}) {
  const template = translations[locale]?.[key] ?? translations.en[key] ?? key;
  return Object.entries(replacements).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    template,
  );
}
